// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: KLog.proto

package klog

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     int64          `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Contents []*Log_Content `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KLog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_KLog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_KLog_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Log) GetContents() []*Log_Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

type LogGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs     []*Log `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Reserved string `protobuf:"bytes,2,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Filename string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Source   string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *LogGroup) Reset() {
	*x = LogGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KLog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogGroup) ProtoMessage() {}

func (x *LogGroup) ProtoReflect() protoreflect.Message {
	mi := &file_KLog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogGroup.ProtoReflect.Descriptor instead.
func (*LogGroup) Descriptor() ([]byte, []int) {
	return file_KLog_proto_rawDescGZIP(), []int{1}
}

func (x *LogGroup) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *LogGroup) GetReserved() string {
	if x != nil {
		return x.Reserved
	}
	return ""
}

func (x *LogGroup) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *LogGroup) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type LogGroupList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogGroupList []*LogGroup `protobuf:"bytes,1,rep,name=logGroupList,proto3" json:"logGroupList,omitempty"`
}

func (x *LogGroupList) Reset() {
	*x = LogGroupList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KLog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogGroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogGroupList) ProtoMessage() {}

func (x *LogGroupList) ProtoReflect() protoreflect.Message {
	mi := &file_KLog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogGroupList.ProtoReflect.Descriptor instead.
func (*LogGroupList) Descriptor() ([]byte, []int) {
	return file_KLog_proto_rawDescGZIP(), []int{2}
}

func (x *LogGroupList) GetLogGroupList() []*LogGroup {
	if x != nil {
		return x.LogGroupList
	}
	return nil
}

type Log_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Log_Content) Reset() {
	*x = Log_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KLog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Content) ProtoMessage() {}

func (x *Log_Content) ProtoReflect() protoreflect.Message {
	mi := &file_KLog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Content.ProtoReflect.Descriptor instead.
func (*Log_Content) Descriptor() ([]byte, []int) {
	return file_KLog_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Log_Content) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Log_Content) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_KLog_proto protoreflect.FileDescriptor

var file_KLog_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x4b, 0x4c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x6b,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0x81, 0x01, 0x0a, 0x03, 0x4c, 0x6f, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x31, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7f, 0x0a, 0x08,
	0x4c, 0x6f, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x48, 0x0a,
	0x0c, 0x4c, 0x6f, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x38, 0x0a,
	0x0c, 0x6c, 0x6f, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x2e, 0x4c, 0x6f, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_KLog_proto_rawDescOnce sync.Once
	file_KLog_proto_rawDescData = file_KLog_proto_rawDesc
)

func file_KLog_proto_rawDescGZIP() []byte {
	file_KLog_proto_rawDescOnce.Do(func() {
		file_KLog_proto_rawDescData = protoimpl.X.CompressGZIP(file_KLog_proto_rawDescData)
	})
	return file_KLog_proto_rawDescData
}

var file_KLog_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_KLog_proto_goTypes = []interface{}{
	(*Log)(nil),          // 0: akTransfer.Log
	(*LogGroup)(nil),     // 1: akTransfer.LogGroup
	(*LogGroupList)(nil), // 2: akTransfer.LogGroupList
	(*Log_Content)(nil),  // 3: akTransfer.Log.Content
}
var file_KLog_proto_depIdxs = []int32{
	3, // 0: akTransfer.Log.contents:type_name -> akTransfer.Log.Content
	0, // 1: akTransfer.LogGroup.logs:type_name -> akTransfer.Log
	1, // 2: akTransfer.LogGroupList.logGroupList:type_name -> akTransfer.LogGroup
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_KLog_proto_init() }
func file_KLog_proto_init() {
	if File_KLog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_KLog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KLog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KLog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogGroupList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KLog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_KLog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_KLog_proto_goTypes,
		DependencyIndexes: file_KLog_proto_depIdxs,
		MessageInfos:      file_KLog_proto_msgTypes,
	}.Build()
	File_KLog_proto = out.File
	file_KLog_proto_rawDesc = nil
	file_KLog_proto_goTypes = nil
	file_KLog_proto_depIdxs = nil
}
